### ISSUE TITLE
Give me the reupload command without a Donator/Server-Boosting

### ISSUE THREAD

**Issue by Rxntiongaming** [MathieuARS/GDPS-Free-Hosting_Guardian#2]
Plz

**Comment by MathieuARS** [comment]
What does that have anything to do with the guardian bot? and no you can't get it for free

**Comment by Rxntiongaming** [comment]
> What does that have anything to do with the guardian bot? and no you can't get it for free

Why it's just a bot command only reupload youtube video

**Comment by Rxntiongaming** [comment]
Cause I'm Trying To Make A Bot & I Need 1 more command I just need a yt reupload command 🙄🙄🙄

**Comment by Optimal7** [comment]
Then learn to code
